-- Seed Court
insert into public.court (name, location, operating_hours)
values ('PickleBall Arena', 'Downtown Sports Complex', '{"open": "06:00", "close": "23:00"}');

-- Seed Membership Plans
insert into public.membership_plans (name, price_monthly, benefits) values
('Silver', 999, '{"discount_percent": 5, "priority_hours": 24}'),
('Gold', 1999, '{"discount_percent": 15, "priority_hours": 48}'),
('Pro', 4999, '{"discount_percent": 25, "priority_hours": 72, "free_sessions": 4}');

-- Seed Basic Slots (Example for one day)
-- In production, these would be generated by a function or cron job
do $$
declare
  court_id uuid;
begin
  select id into court_id from public.court limit 1;
  
  -- Create slots from 6am to 10pm for today
  -- This is just illustrative SQL, typically done via App logic
end $$;
